### ISSUE TITLE
schelp documents are not well formatted

### ISSUE THREAD

**Issue by geoffroymontel** [salkin-mada/vscode_supercollider#4]
Thanks for the VSCode extension !
All the `.schelp` files are weirdly formatted. Could you disable formatting on these files please ?

**Comment by salkin-mada** [comment]
Thanks for opening this issue.
Will look into it asap.

**Comment by geoffroymontel** [comment]
Thanks !!

**Comment by salkin-mada** [comment]
Could you elaborate on the trouble with the formatting of `.schelp` files?

**Comment by salkin-mada** [comment]
I would like to keep formatting in `.schelp` files. so that they get formatted the same way as in `scide`.
I think the problem with formatting that you experience is not only in `.schelp` files but is actually a bug in general with the regex for single and double quotes. This is related to #2

**Comment by salkin-mada** [comment]
@geoffroymontel the extension at [visual studio code marketplace](https://marketplace.visualstudio.com/items?itemName=salkin-mada.language-supercollider) has been updated.
I have fixed bugs regarding single-quotes, char signage `$a`, multi-line/block comment and keywords like `this.` and `super.`
now `.schelp`, `.sc` and `.scd` files should be formatted in the same way as scide + the additions.
Let me know if this solves your schelp documents trouble.

**Comment by geoffroymontel** [comment]
Dear @salkin-mada, sorry for the delay in my reply.
Thanks for the update !
You're right, the .schelp documents are formatted the same way as in SCIde.
It's not so bad ! The only thing is that schelp documents are not SC documents, and they would require a different parser. But it's definitely usable and the only drawback is that some words are coloured where it does not make sense.

For instance :
<img width="787" alt="Capture d’écran 2019-08-08 à 11 53 17" src="https://user-images.githubusercontent.com/352910/62693630-27e3f680-b9d3-11e9-95d8-f55a98631fc9.png">

In an ideal world, `When`,  `this`, `function:`, `For` should not be in a different color, but that's really a detail.
Thanks for your work !
